/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: builtin.h
  Source: builtin.idl
  Cyclone DDS: V0.10.0

*****************************************************************/
#ifndef DDSC_BUILTIN_H
#define DDSC_BUILTIN_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct NameValue
{
  int32_t sn;
  char * name;
  char * value;
} NameValue;

extern const dds_topic_descriptor_t NameValue_desc;

#define NameValue__alloc() \
((NameValue*) dds_alloc (sizeof (NameValue)));

#define NameValue_free(d,o) \
dds_sample_free ((d), &NameValue_desc, (o))

typedef struct KeyValue
{
  int32_t sn;
  char * key;
  char * value;
} KeyValue;

extern const dds_topic_descriptor_t KeyValue_desc;

#define KeyValue__alloc() \
((KeyValue*) dds_alloc (sizeof (KeyValue)));

#define KeyValue_free(d,o) \
dds_sample_free ((d), &KeyValue_desc, (o))

#ifndef DDS_SEQUENCE_OCTET_DEFINED
#define DDS_SEQUENCE_OCTET_DEFINED
typedef struct dds_sequence_octet
{
  uint32_t _maximum;
  uint32_t _length;
  uint8_t *_buffer;
  bool _release;
} dds_sequence_octet;

#define dds_sequence_octet__alloc() \
((dds_sequence_octet*) dds_alloc (sizeof (dds_sequence_octet)));

#define dds_sequence_octet_allocbuf(l) \
((uint8_t *) dds_alloc ((l) * sizeof (uint8_t)))
#endif /* DDS_SEQUENCE_OCTET_DEFINED */

typedef struct NamedBlob
{
  int32_t sn;
  char * name;
  dds_sequence_octet value;
} NamedBlob;

extern const dds_topic_descriptor_t NamedBlob_desc;

#define NamedBlob__alloc() \
((NamedBlob*) dds_alloc (sizeof (NamedBlob)));

#define NamedBlob_free(d,o) \
dds_sample_free ((d), &NamedBlob_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_BUILTIN_H */
