struct NameValue {
    long sn;
    string name;
    string value;
};
#pragma keylist NameValue

struct KeyValue {
    long sn;
    string key;
    string value;
};

#pragma keylist KeyValue key

struct NamedBlob {
    long sn;
    string name;
    sequence<octet> value;
};

#pragma keylist NamedBlob name
