@final
struct NameValue {
    long sn;
    string name;
    string value;
};

@final
struct KeyValue {
    long sn;
    @key string key;
    string value;
};

@final
struct NamedBlob {
    long sn;
    @key string name;
    sequence<octet> value;
};
