/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: cdds_builtin.c
  Source: cdds_builtin.idl
  Cyclone DDS: V0.7.0

*****************************************************************/
#include "cdds/cdds_builtin.h"


static const uint32_t NameValue_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (NameValue, sn),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (NameValue, name),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (NameValue, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t NameValue_desc =
{
  sizeof (NameValue),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "NameValue",
  NULL,
  4,
  NameValue_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"NameValue\"><Member name=\"sn\"><Long/></Member><Member name=\"name\"><String/></Member><Member name=\"value\"><String/></Member></Struct></MetaData>"
};


static const dds_key_descriptor_t KeyValue_keys[1] =
{
  { "key", 2 }
};

static const uint32_t KeyValue_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (KeyValue, sn),
  DDS_OP_ADR | DDS_OP_TYPE_STR | DDS_OP_FLAG_KEY, offsetof (KeyValue, key),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (KeyValue, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t KeyValue_desc =
{
  sizeof (KeyValue),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  1u,
  "KeyValue",
  KeyValue_keys,
  4,
  KeyValue_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"KeyValue\"><Member name=\"sn\"><Long/></Member><Member name=\"key\"><String/></Member><Member name=\"value\"><String/></Member></Struct></MetaData>"
};


static const dds_key_descriptor_t NamedBlob_keys[1] =
{
  { "name", 2 }
};

static const uint32_t NamedBlob_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (NamedBlob, sn),
  DDS_OP_ADR | DDS_OP_TYPE_STR | DDS_OP_FLAG_KEY, offsetof (NamedBlob, name),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (NamedBlob, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t NamedBlob_desc =
{
  sizeof (NamedBlob),
  sizeof (char *),
  DDS_TOPIC_NO_OPTIMIZE,
  1u,
  "NamedBlob",
  NamedBlob_keys,
  4,
  NamedBlob_ops,
  "<MetaData version=\"1.0.0\"><Struct name=\"NamedBlob\"><Member name=\"sn\"><Long/></Member><Member name=\"name\"><String/></Member><Member name=\"value\"><Sequence><Octet/></Sequence></Member></Struct></MetaData>"
};
