/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: builtin.c
  Source: builtin.idl
  Cyclone DDS: V0.10.0

*****************************************************************/
#include "cdds/cdds_builtin.h"

static const uint32_t NameValue_ops [] =
{
  /* NameValue */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (NameValue, sn),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (NameValue, name),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (NameValue, value),
  DDS_OP_RTS
};

const dds_topic_descriptor_t NameValue_desc =
{
  .m_size = sizeof (NameValue),
  .m_align = dds_alignof (NameValue),
  .m_flagset = 0u,
  .m_nkeys = 0u,
  .m_typename = "NameValue",
  .m_keys = NULL,
  .m_nops = 4,
  .m_ops = NameValue_ops,
  .m_meta = ""
};

static const uint32_t KeyValue_ops [] =
{
  /* KeyValue */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (KeyValue, sn),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_STR, offsetof (KeyValue, key),
  DDS_OP_ADR | DDS_OP_TYPE_STR, offsetof (KeyValue, value),
  DDS_OP_RTS,
  
  /* key: key */
  DDS_OP_KOF | 1, 2u /* order: 1 */
};

static const dds_key_descriptor_t KeyValue_keys[1] =
{
  { "key", 7, 0 }
};

const dds_topic_descriptor_t KeyValue_desc =
{
  .m_size = sizeof (KeyValue),
  .m_align = dds_alignof (KeyValue),
  .m_flagset = 0u,
  .m_nkeys = 1u,
  .m_typename = "KeyValue",
  .m_keys = KeyValue_keys,
  .m_nops = 4,
  .m_ops = KeyValue_ops,
  .m_meta = ""
};

static const uint32_t NamedBlob_ops [] =
{
  /* NamedBlob */
  DDS_OP_ADR | DDS_OP_TYPE_4BY | DDS_OP_FLAG_SGN, offsetof (NamedBlob, sn),
  DDS_OP_ADR | DDS_OP_FLAG_KEY | DDS_OP_FLAG_MU | DDS_OP_TYPE_STR, offsetof (NamedBlob, name),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (NamedBlob, value),
  DDS_OP_RTS,
  
  /* key: name */
  DDS_OP_KOF | 1, 2u /* order: 1 */
};

static const dds_key_descriptor_t NamedBlob_keys[1] =
{
  { "name", 7, 0 }
};

const dds_topic_descriptor_t NamedBlob_desc =
{
  .m_size = sizeof (NamedBlob),
  .m_align = dds_alignof (NamedBlob),
  .m_flagset = 0u,
  .m_nkeys = 1u,
  .m_typename = "NamedBlob",
  .m_keys = NamedBlob_keys,
  .m_nops = 4,
  .m_ops = NamedBlob_ops,
  .m_meta = ""
};

